feat: add home page ( user-main-2 )
isd-sgcu/johnjud-frontend pull request #14
Opened 2024-01-03 09:33 UTC by punchanabu

2024-01-05 12:07 UTC, boomchanotai requested changes
commented!

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Divider/DividerMobile.tsx
ฝากยุบรวมกับ Divider หน่อย แบบเอาเป็น Divider ตัวเดียวแล้ว responsive เอาอ่ะ ขอโทษที ใน figma ถ้ามีตามหลังด้วย mobile คือจะให้ทำ responsive อ่ะๆ

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Divider/Divider.tsx
> +      <Icon icon="ph:paw-print" className="h-9 w-9 text-primary" />
ฝากเพิ่ม reponsive และยุบ DividerMobile มารวมๆ

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Main/Heading/MobilePetsHeading.tsx
ผมว่าอันนี้ทั้ง Mobile และ Desktop ใช้อันเดียวกันไปเลย แล้วก็ใช้ Heading Component `src/components/Pets/Heading.tsx` ผมเลยก็ได้ เดี๋ยวแก้ Figma ให้ 

แต่ฝากไปแก้แบบใส่ props เพิ่มหน่อย น่าจะต้องรับ `onSearch` มา ถ้า true จะให้ใช้ข้อความ "พบสัตว์เลี้ยงทั้งหมด" ถ้า false จะเป็น "สัตว์เลี้ยงมากกว่า" ขนาดเอาตามนั้นเลย Mobile ไม่ต้องเล็ก ขอโทษที่ไม่ได้ดูตรงนี้ดีๆค้าบ 🙏

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Main/Heading/PetsHeading.tsx
อันนี้ดูตาม comment ในไฟล์ MobilePetsHeading.tsx เลย

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Main/SearchFilter/Search.tsx
ฝากย้ายไปอยู่ที่ `src/components/Search` แทน

2024-01-05 12:07 UTC, boomchanotai commented on src/components/Main/SearchFilter/Filter.tsx
ฝาก refactor ไปใช้ components Button ของผมหน่อยนะๆ `src/components/Button.tsx`

2024-01-05 15:02 UTC, punchanabu commented
- รวม Divider เป็นหนึ่งเดียว 
- ใช้ Heading จาก /pets และ เพิ่ม onSearch เป็น props แล้ว มีตัวแปร displayText คำณวนจาก prop ว่าจะต้องแสดงอะไร
- ย้าย Search.tsx ไป /Search folder และ เปลี่ยนชื่อเป็น PetSearchGreen 
- Refactor Filter.tsx โดยใช้ component Button.tsx ที่เป็นของกลาง

2024-01-06 03:21 UTC, boomchanotai requested changes
commented!

2024-01-06 03:21 UTC, boomchanotai commented on src/components/Pets/Heading.tsx
> +  const displayText = onSearch ? "พบสัตว์เลี้ยงทั้งหมด" : "สัตว์เลี้ยงมากกว่า";
ครอบ `useMemo` ดีกว่า เพราะว่า useMemo จะ cache ตัวแปรไว้ ถ้า re-render มันจะไม่เสียพลังงานไปประมวลผลใหม่

2024-01-06 03:21 UTC, boomchanotai commented on src/components/Search/PetSearchGreen.tsx
คิดไปคิดมา file นี้น่าจะรวม component กับ search ของผมได้เลย ฝากทำ variant ให้มันมีสีเขียวให้หน่อยๆ

2024-01-06 03:21 UTC, boomchanotai commented on src/components/Main/Filter.tsx
Button ใช้ rounded-2xl ให้หมดเลยดีกว่า

ฝาก pass props `rounded="2xl"` เข้าไปด้วย

2024-01-06 18:26 UTC, boomchanotai approved these changes
Perfect !

2024-01-06 19:29 UTC, merged