feat: VERY ULTRA SUPER BIG HUGE PET CARD
isd-sgcu/johnjud-frontend pull request #18
Opened 2024-01-04 19:45 UTC by ChanatpakornD

- Added big PetCard
- Added user & admin big petCard
- Added 2 new components namely PetDescription and TogglePetButton

2024-01-05 02:20 UTC, boomchanotai requested changes
อ่าน comment ซะ

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petDescription.tsx
ชื่อไฟล์ Component ต้องพิมพ์ใหญ่

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petCard.tsx
Redundant Naming ให้แก้ชื่อไฟล์นี้เป็น index.tsx แทน มันจะเรียกใช้งานโดยใช้ `@/components/PetCard` แทน

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petDescription.tsx
> +const petDescription = (props: PetDescriptionProps) => {
ชื่อ Component พิมพ์ใหญ่ตัวแรก `petDescription` => `PetDescription`

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petDescription.tsx
> +      <span className="">{props.description}</span>
ลบ className="" ออกด้วย ถ้าไม่ได้ใช้

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petDescription.tsx
> +        color={props.color}
ทำไมต้องรับสีมาด้วย มันเป็นสีเทาล้วนไม่ใช่หรอ

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petCard.tsx
> +              color={"#808086"}
ใส่สีเป็น Class แทน ว่าแต่จะ pass สีไปทำไม

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petCard.tsx
> +          alt="_blank"
alt="text" มันคือ ที่เอาไว้บอกผู้พิการทางสายตาว่านี่คือรูปอะไร เปลี่ยนซะ

2024-01-05 02:20 UTC, boomchanotai commented on src/components/PetCard/petCard.tsx
> +            variant={isAdopted}
WTF มี variant นี้ด้วยหรอ

2024-01-05 07:44 UTC, ChanatpakornD commented
- Change filename components to `PetDescriptinText` cuz one letter casing cannot been formatted
- Change like u tolded
- className deletion
- not pass down color anymore
- added type of pet  in props of card to give `alt` the text

2024-01-05 11:46 UTC, boomchanotai requested changes
โปรดแก้

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/PetDescriptionText.tsx
> +    <div className="mb-1 flex items-center gap-2 text-base font-normal text-zinc-500">
`text-zinc-500` shouldn't be used! `text-accent-gray` instead!

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/PetDescriptionText.tsx
> +const PetDescriptionText = (props: PetDescriptionProps) => {
เปลี่ยนเป็นชื่อ PetDetail ก็ได้ อันนี้ยาวไป หมายถึงชื่อไฟล์และ Component เลยนะ

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/TogglePetButton.tsx
> +        }`}
สนใจลอง [Tailwind Variants](https://www.tailwind-variants.org/) ไหม จะได้เขียนพวก variants ได้สวยๆ

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  onClick,
ไม่ต้องมี default ยกเว้น isLiked

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  age = "อายุ 6 ปี 11 เดือน",
age ให้รับเป็น birthdate แล้วมา format เอาในนี้ ผ่านการใช้ useMemo

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  age = "อายุ 6 ปี 11 เดือน",
หมายถึงรับเป็น string of birthdate

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  if (role === "user" && isVisibled === true) {
ควร เอา if ตรงนี้ไปอยู่ตรงปุ่มแทน เพราะส่วนอื่นของ components มันเหมือนกัน

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +              color={"#C81425"}
เปลี่ยนไปใช้ className="text-accent-red"

2024-01-05 11:46 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +              color={"#C81425"}
เปลี่ยนไปใช้ className="text-accent-red"

2024-01-05 17:22 UTC, ChanatpakornD commented on src/components/PetCard/index.tsx
> +  if (role === "user" && isVisibled === true) {
แล้วเรื่องของ Visible อ่ะ admin เห็นแต่ user ไม่เห็น สุดท้ายก็ต้องแยกป่ะ

2024-01-07 14:31 UTC, ChanatpakornD commented
lazy to comment la
- using useMemo
- merge dev
- changes

2024-01-07 14:45 UTC, boomchanotai requested changes
Commented !

2024-01-07 14:45 UTC, boomchanotai commented on src/components/PetCard/PetDetail.tsx
> +    <div className="mb-1 flex items-center gap-2 text-base font-normal text-accent-gray">
ไม่ต้องมี `mb-1` แล้วถ้าจะใช้ flex ก็ใช้ `div` ครอบ `iconify` กับ `div` แทน `span`

2024-01-07 14:45 UTC, boomchanotai commented on package.json
> +    "utc": "link:dayjs/plugin/utc"
delete

2024-01-07 14:45 UTC, boomchanotai commented on src/components/PetCard/TogglePetButton.tsx
> +  const text = isVisible ? "มองเห็น" : "ปิดการมองเห็น";
useMemo

2024-01-07 14:45 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  role: "user" | "admin";
ไม่ต้องรับ role ละกัน

2024-01-07 14:45 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  role: "user" | "admin";
ทำ useMemo ไว้ตัวนึงไว้รับ role จาก state manager ตัวอื่น แบบ

```
const role = useMemo(() => {
return "user"
}, [])
```

2024-01-07 15:43 UTC, ChanatpakornD commented
AsUrWishes

2024-01-07 16:36 UTC, boomchanotai requested changes
คือ `isVisibled` อ่ะ จะไปเช็คตอน forloop แทนว่าจะเรียก components นี้ไหม เพราะฉนั้นไม่ต้อง pass มา

2024-01-07 16:36 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  if (role === "user" && isVisibled === false) {
ลบ

2024-01-07 16:36 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  isVisibled,
ลบ

2024-01-07 16:43 UTC, boomchanotai requested changes
เอา `src/app/testpage` ออกได้เลย

2024-01-07 16:49 UTC, boomchanotai requested changes

2024-01-07 16:49 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +  } else {
ลบเพราะว่าเราจะไปสั่ง render ไหมนี่ไปจัดการที่ mapping function แทน

2024-01-07 16:49 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +              <TogglePetButton visibility={isVisibled} />
ปุ่ม toggle กดไม่ได้

2024-01-07 16:49 UTC, boomchanotai commented on src/components/PetCard/index.tsx
> +    return "/pets/" + id;
ถ้าเป็น role admin จะให้ linkTo={`/admin/pets/${id}/edit`}

2024-01-08 04:56 UTC, ChanatpakornD commented
As your wishes pt.2

2024-01-08 06:09 UTC, boomchanotai requested changes
Delete testpage

2024-01-08 06:11 UTC, boomchanotai approved these changes
สุดยอดเลยครับพรี่ พรี่ว่าไงผมว่างั้นจั๊ฟ

2024-01-08 06:12 UTC, merged