Tee/feat/new navbar
isd-sgcu/johnjud-frontend pull request #19
Opened 2024-01-05 15:02 UTC by TeeGoood

2024-01-05 18:38 UTC, boomchanotai requested changes
ฝากดูตาม comment ไฟล์ แล้วก็
- ลบ icon ใน `src/assets` ที่ไม่จำเป็นออก น่าจะเหลือแค่ logo 2 ไฟล์นะ
- เปลี่ยนชื่อ folder จาก `navbar` เป็น `Navbar`

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/Navbar.tsx
Files นี้คืออะไร ยังจำเป็นไหม

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/index.tsx
เปลี่ยนชื่อ folder `navbar` เป็น `Navbar`

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +  useMemo(() => {
ใช้ useEffect แทน

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +import SideBarWrapper from "./SideBarWrapper";
ลองลบและ import ใหม่หน่อย เหมือนมันบัคๆงงๆ

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +      />
use `iconify` instead

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +            <Icon icon={"ph:house"} color="white" className="h-6 w-6" />
refactor นิดนึง `<Icon icon={"ph:house"} color="white" className="h-6 w-6" />` => `<Icon icon="ph:house" color="white" className="h-6 w-6" />`

2024-01-05 18:38 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +    <div className={`h-full px-8 py-6 text-sm text-white xl:p-16 ${color}`}>
ฝากใส่ Shadow นิดหน่อย ให้เห็นว่าลอยอยู่อ่ะ

2024-01-06 06:53 UTC, TeeGoood commented on src/components/navbar/index.tsx
> +  useMemo(() => {
code ในส่วนนี้กูเปลี่ยนเเปลงนะ
- กูเก็บ style ต่างๆไว้ใน state เเทน
- update style ตาม pathname ของเพจนั้นๆ

2024-01-06 07:02 UTC, TeeGoood commented on src/components/navbar/SideBar.tsx
> +    <div className={`h-full px-8 py-6 text-sm text-white xl:p-16 ${color}`}>
ใส่ไปละดูให้หน่อยว่าโอเคมั้ย

2024-01-06 07:02 UTC, TeeGoood commented on src/components/navbar/index.tsx
> +import SideBarWrapper from "./SideBarWrapper";
ทำละยังบัคอยู่มั้ย 
กู run เเล้วไม่มีปัญหานะ

2024-01-06 07:09 UTC, TeeGoood commented
กู pnpm lint:fix ไปละเเต่ทำไม lint pull request มันไม่ผ่านวะ

2024-01-06 18:27 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +import SideBarWrapper from "./SideBarWrapper";
ok

2024-01-06 18:45 UTC, boomchanotai requested changes
- ฝากลบ `src/components/Navbar.tsx` ที่กูทำไว้หน่อย
- เปลี่ยนชื่อ folder มันไม่ติดใน github เพราะว่ามันติดที่พิมพ์เล็กพิมพ์ใหญ่ เดี๋ยวขอลองหาวิธีก่อน

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +import blankProfile from "../../assets/Navbar/blankProfile.svg";
ใช้ import alias แทน => `@/assets/Navbar/blankProfile.svg`

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +        </span>
ยัด Link to="/login" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/home" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/pets" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/game" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/horo" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/frequently-asked-questions" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/about" เลย

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/SideBar.tsx
> +          </div>
ยัด Link to="/admin" เลย แต่ เปลี่ยนคำเป็น Admin

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +import logoPrimary from "../../assets/Navbar/logoPrimary.svg";
ใช้ import alias แทน => `@/assets/Navbar/logoPrimary.svg`

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +import logoSecondary from "../../assets/Navbar/logoSecondary.svg";
ใช้ import alias แทน => `@/assets/Navbar/logoSecondary.svg`

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +      <div className="h-18 flex items-center gap-3 ">
ไม่ต้อง `h-18` ให้มัน dynamic ไป

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +        color="white"
เปลี่ยนไปใช้ `className="text-white"`

2024-01-06 18:45 UTC, boomchanotai commented on src/components/navbar/index.tsx
> +  }, [pathname]);
โอเค ถ้าจะทำแบบนี้ควรยุบเหลือ useMemo ตัวเดียว จะได้ประสิทธิภาพที่ดีกว่า

เหตุผลคือ ตอนที่ component นี้ถูก render มันจะทำการเรียก useEffect และ มันจะไป useState ก็คือ re-render เราสามารถรวมสองตัวนี้ด้วย useMemo ได้ เพราะระหว่างทางมันก็ไม่ได้เปลี่ยนอะไรอยู่แล้ว

ก็คือ `const style = useMemo(() => {}, [pathname])`

function ข้างในก็ใส่ตามใน useEffect เลย แต่เปลี่ยนจาก setStyle เป็น return ออกมาแทน

2024-01-07 11:37 UTC, boomchanotai requested changes
last 3 comment !

2024-01-07 11:37 UTC, boomchanotai commented on src/components/Navbar/index.tsx
> +      <div className="flex items-center gap-3 ">
ลบ เว้นวรรคตรงข้างหลังสุดให้หน่อย

2024-01-07 11:37 UTC, boomchanotai commented on src/components/Navbar/Page.tsx
ไม่ได้ใช้ไฟล์นี้แล้วหนิ

2024-01-07 11:37 UTC, boomchanotai commented on src/components/Navbar/SideBarWrapper.tsx
> +  const opacity = toggle ? "opacity-1" : "opacity-0";
Wrap this one with useMemo เพราะว่าไม่งั้นมันจะไม่ detect เวลา state เปลี่ยน

2024-01-07 13:53 UTC, boomchanotai requested changes

2024-01-07 13:53 UTC, boomchanotai commented on src/components/Navbar/SideBarWrapper.tsx
> +  }
อันนี้ครอบ useCallback หน่อย

2024-01-07 16:53 UTC, boomchanotai approved these changes
Perfect !

2024-01-08 03:10 UTC, merged