Feature/joh 22 user create
isd-sgcu/johnjud-frontend pull request #20
Opened 2024-01-05 18:19 UTC by ThanaphomH

- User create page for admin (/admin/user-create)
- Pet badge component and related components (at /components/admin/user-create)

Problem
- At EditName, text need to be break-all (Did not spectific width)
- At AddSmallPictures, when hide scrollbar cannot drag to slide so scrollbar need to be shown

2024-01-06 04:40 UTC, boomchanotai requested changes
Commented!

2024-01-06 04:40 UTC, boomchanotai commented on package.json
> +    "@iconify/react": "^4.1.1",
เอานี่ย้ายไปอยู่ใน `devDependencies` แทน (ไปก็อป package.json จาก dev มา)

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/PetBadge.tsx
> +    <path d="M16.5 11.2502C16.5 12.4437 16.0259 13.5883 15.182 14.4322C14.3381 15.2761 13.1935 15.7502 12 15.7502M12 15.7502C9.50272 14.2519 6.63461 14.4166 4.99702 14.6938C4.58204 14.7646 4.15553 14
เอา custom iconify ไปใส่ใน `src/utils/iconify`

2024-01-06 04:40 UTC, boomchanotai commented on src/app/admin/user-create/page.tsx
please refactor folder to `src/app/admin/pets/add`

2024-01-06 04:40 UTC, boomchanotai commented on package.json
> +    "@iconify/react": "^4.1.1",
ถ้าก็อป package.json ใน dev อย่าลืมเอา "react-autosize-textarea": "^7.1.0" มาใส่ด้วยนะ

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/AddThumpnail.tsx
change file name and component name `Thumpnail` => `Thumbnail`

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/AddThumpnail.tsx
move `iconify` to `src/utils/iconify`

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/AddThumpnail.tsx
ถ้ายังไม่มีรูปเลย ไม่ต้องขึ้น ดินสอ ให้ปุ่มบวกคือตัวกดเพิ่มรูปภาพ
แต่ถ้ามีรูปแล้วก็ไม่ต้องมีปุ่มบวก และขึ้นรูปดินสอให้ edit

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +                <Icon icon="ph:paw-print" className="h-5 w-5" color="#08878E" />
`color` ใช้เป็น `className="text-primary"` แทน

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +                    color="#C81425"
`color` ใช้เป็น `className="text-accent-red"` แทน  ฝากแก้ที่เหลือด้วย

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
ตรง edit ถ้ากำลังเปิด mode edit อยู่ ฝากทำให้ปุ่ม ดินสอ กลายเป็นปุ่ม save หน่อย

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/EditName.tsx
ฝากมีปุ่ม save ข้างหลังกล่องข้อความหน่อย

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/EditText.tsx
ฝากทำ ปุ่ม save ด้วยไว้ ลืมทำให้ใน figma โทษที เอาไว้ล่างกล่อง ชิดขวา ละกัน

2024-01-06 04:40 UTC, boomchanotai commented on src/components/admin/user-create/PetBadge.tsx
move `iconify` to `src/utils/iconify`

2024-01-06 04:40 UTC, boomchanotai commented on src/app/admin/user-create/page.tsx
ฝากเอา Component : Container ของผมที่อยู่ `src/components/Container` มาครอบแต่ละ block หน่อย ยกเว้นอันที่มันเต็มจอนะ ๆ

2024-01-07 06:58 UTC, ThanaphomH commented
แก้หมดละฮับ

2024-01-07 14:25 UTC, boomchanotai requested changes
Commented!

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/PetBadge.tsx
> +        color={props.value === "fromClub" ? "#08878E" : "#FFFF31"}
เปลี่ยนเป็น `className="text-"` แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +        </div>
อันนี้เปลี่ยนไปใช้ร่วมกับ desktop เลย หมายถึงว่าให้มันอยู่ใน frame เลย

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +              </div>
ฝากใช้ Button Component `src/components/Button`

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +              <div
ฝากใช้เป็น tag button แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +              <div
ฝากใช้เป็น tag button แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +                  enableEdit ? "border border-[#D9D9D9]" : ""
ฝากเพิ่ม `"accent-gray-variant": "#D9D9D9"` ใน tailwind.config.js บรรทัดต่อจาก accent-gray หน่อย  แล้วใช้ `border-accent-gray-variant` แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +                  enableEdit ? "border border-[#D9D9D9]" : ""
ฝากเพิ่ม `"accent-gray-variant": "#D9D9D9"` ใน tailwind.config.js บรรทัดต่อจาก accent-gray หน่อย  แล้วใช้ `border-accent-gray-variant` แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +                  enableEdit ? "border border-[#D9D9D9]" : ""
ฝากเพิ่ม `"accent-gray-variant": "#D9D9D9"` ใน tailwind.config.js บรรทัดต่อจาก accent-gray หน่อย  แล้วใช้ `border-accent-gray-variant` แทน

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +              <div
จริงๆใช้เป็น component ร่วมกับทำหมันเลยก็ได้นะ แบบทำมา component เดียว แล้ว pass props พวกชื่อ บลาๆๆ เข้าไป

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +              <div
จริงๆใช้เป็น component ร่วมกับทำหมันเลยก็ได้นะ แบบทำมา component เดียว แล้ว pass props พวกชื่อ บลาๆๆ เข้าไป

2024-01-07 14:25 UTC, boomchanotai commented on src/components/admin/user-create/AddThumbnail.tsx
> +        <div className="flex h-full w-full items-center justify-center rounded-3xl border-2 border-[#D9D9D9] bg-white drop-shadow-sm">
ฝากเพิ่ม "accent-gray-variant": "#D9D9D9" ใน tailwind.config.js บรรทัดต่อจาก accent-gray หน่อย แล้วใช้ border-accent-gray-variant แทน

2024-01-07 18:57 UTC, ThanaphomH commented
แก้หมดละฮับ

2024-01-08 01:34 UTC, boomchanotai requested changes
Commented!

2024-01-08 01:34 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
- 2 ก้อนบน (ใส่ชื่อใส่รูป, ใส่ additionalImage) อยากให้เป็นใช้ <Container /> ไปเลยไม่ต้องตี grid แล้ว flex แทน
- เอา grid เอาไปใช้แค่ตรงรายละเอียด
- ตรง ลูกศรกลับ lg ให้ px-12 เป็น full-width div

<img width="628" alt="Screenshot 2567-01-08 at 08 30 07" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/fda60003-a11b-4aff-a878-9748ad456af2">

2024-01-08 01:34 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
> +    <div className="grid w-screen grid-cols-1 flex-col pb-28 lg:grid-cols-3 lg:pb-20">
ตรงนี้เป็น Fragment แทน เพราะว่าอยากให้ใช้ xl:space-y-10 space-y-6 จาก Layout แทน

2024-01-08 11:46 UTC, boomchanotai requested changes
เปลี่ยน folder `src/components/admin` เป็น `src/components/Admin`

```bash
git mv src/components/admin src/components/admin2
git mv src/components/admin2 src/components/Admin
```

และ `src/components/admin/user-create` เป็น `src/components/Admin/Pets/Add`

2024-01-08 11:46 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
> +      </div>
```suggestion
      <Container className="flex flex-col gap-8 md:flex-row">
        {/* Thumpnail */}
        <div className="w-full md:w-80">
          <AddThumbnail
            valueThumbnail={thumbnail}
            setThumbnail={setThumbnail}
            valueOrigin={origin}
            setOrigin={setOrigin}
          />
        </div>

        {/* large EditName + EditText */}
        <div className="flex w-full flex-col md:justify-between md:gap-4">
          <div className="hidden w-full md:flex md:flex-col">
            <EditName value={name} setValue={setName} />
          </div>
          <EditText value={text} setValue={setText} />
        </div>
      </Container>
```

2024-01-08 11:46 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
> +      </div>
```suggestion
      <Container>
        <AddSmallPicture value={pictures} setValue={setPictures} />
      </Container>
```

2024-01-08 11:46 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
> +        </Container>
ตรงนี้ไม่ต้องครอบ Container ก็ได้ ที่ให้ครอบ Container คืออยากให้มันเป็น Convention ซ้ายขวาเท่ากันทุกหน้าเหมือนใน Figma

2024-01-08 11:46 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +      <div className="flex w-full flex-col border-2 border-accent-gray-variant border-opacity-50 bg-white px-6 py-6 lg:rounded-2xl lg:py-8 lg:pl-[12.5%] lg:pr-0">
ใช้ `lg:rounded-r-2xl`

2024-01-08 11:46 UTC, boomchanotai commented on src/components/admin/user-create/EditInfoAndSubmit.tsx
> +      <div className="flex w-full flex-col border-2 border-accent-gray-variant border-opacity-50 bg-white px-6 py-6 lg:rounded-2xl lg:py-8 lg:pl-[12.5%] lg:pr-0">
ใช้ `lg:rounded-r-2xl`

2024-01-08 14:47 UTC, boomchanotai approved these changes
Perfect !

2024-01-08 16:35 UTC, merged