Tee/feat/new user details
isd-sgcu/johnjud-frontend pull request #21
Opened 2024-01-06 06:08 UTC by TeeGoood

2024-01-06 18:49 UTC, boomchanotai requested changes
- เอา components ทั้งหมดไปใส่ใน `src/components/Details`
- มี refactor design นิดหน่อย รบกวนเช็คใน section รายละเอียดของสัตว์หน่อย

2024-01-06 18:49 UTC, boomchanotai commented on src/app/details/BigPetCard.tsx
> +          <p className="text-[32px] font-bold">ไรลีย์</p>
`text-[32px]` เปลี่ยนเป็น `text-4xl` มีแก้ design figma นิดหน่อย

2024-01-06 18:49 UTC, boomchanotai commented on src/app/details/BigPetCard.tsx
> +              color="#c81425"
ใช้ class `text-accent-red`

2024-01-06 18:49 UTC, boomchanotai commented on src/app/details/BigPetCard.tsx
> +          color="#08878E"
ใช้ class `text-primary`

2024-01-06 18:49 UTC, boomchanotai commented on src/app/details/BigPetCard.tsx
> +            color="#c81425"
ใช้ class `text-accent-red`

2024-01-09 08:10 UTC, boomchanotai commented
1. Merge `dev` so you will get components from Don's tasks
2. Your task consists of 2 pages : `/pets/:id` and `/admin/pets/:id/edit` (นี่คือ Link ที่ควรอยู่ใน URL นะ)
3. Refactor following this
- Use `<></>` ครอบทั้ง page เพราะว่าจะใช้ `space-y` ตามใน Layout file ลองดูตัวอย่างการวาง Element ที่ `src/app/pets/page.tsx`
- Wrap this element with `<Container></Container>` from `src/components/Container` อันไหนที่เต็มจอไม่ต้อง Wrap ด้วย `<Container></Container>` นะ
- Reuse `PetBadge` Component from `src/Admin/Pets/Add/PetBadge.tsx` : มันคือตรงมุมของ Thumbnail อ่ะว่าเป็นสัตว์ที่มาจากไหน (ส่วน Thumbnail Picture ของหน้า Role User ธรรมดา ขอเป็น Slideshow Image แล้วมี Badge อยู่ขวาบน / หน้า Admin เอา Component `AddThumbnail` มาใช้ได้เลย)

<img width="640" alt="Screenshot 2567-01-09 at 14 51 33" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/8e6a3c35-9def-4fa7-90de-4883c35d4b3a">

- Reuse `EditName` Component from `src/Admin/Pets/Add/EditName.tsx` : มันสามารถ Edit Name ได้ เอามาใช้กับ Admin ได้เลย
- Reuse `EditText` Component from `src/Admin/Pets/Add/EditText.tsx` : ใช้กับ Admin ได้เลย
- Reuse `AddSmallPicture` Component from `src/Admin/Pets/Add/AddSmallPicture.tsx` : ใช้กับ Admin ได้เลย (ถ้าเป็นหน้า Role User ไม่ต้องมี)
- Reuse `EditInfoAndSubmit` Component from `src/Admin/Pets/Add/EditInfoAndSubmit.tsx` : อาจจะต้องมีหลาย variants หน่อย เพราะว่าหน้า Add จะเป็นปุ่ม "โพสต์เลย", ส่วนหน้า Edit จะเป็นปุ่ม "ถูกรับเลี้ยงแล้ว" กับ "ลบโพสต์"

สามารถ Refactor Component ที่กล่าวมาได้หมดเลย แบบบางอันอาจจะต้องรับ defaultValue จากตอน Edit และบางอันอาจจะต้องรับ Props `editable` เป็น `boolean` เพื่อดูว่า Edit ได้ไหม ถ้า Edit ไม่ได้ คือใช้กับหน้า Role User จะไม่มีปุ่มแก้ไข ส่วน editable: true จะใช้กับหน้า Admin และพฤติกรรมเหมือนกับหน้า `/admin/pets/add` (URL Link)

2024-01-13 15:13 UTC, TeeGoood commented
smallpetcard มันขึ้นต้นด้วยตัวเล็กกูใช้ไม่ได้

2024-01-13 18:39 UTC, boomchanotai requested changes
- ฝากแก้หน้า `/admin/pets/add` หน่อย มันใช้ Components ที่แก้ไป อยากใส่ Props ให้ครบหน่อย
- หน้า `/admin/pets/[id]/edit` บัค เปลี่ยนรูปแล้วรูปกลับไปรูปเดิม เอา State ไปรับให้มันจำค่าด้วย
- Rename `src/components/Pets/details` to `src/components/Pets/Details`
```
git mv src/components/Pets/details src/components/Pets/details2
git mv src/components/Pets/details2 src/components/Pets/Details
```

2024-01-13 18:39 UTC, boomchanotai commented on src/components/Pets/details/PetImgList.tsx
> +        <img src={plusIcon} alt="plus-icon" />
Use `iconify` instead

2024-01-13 18:39 UTC, boomchanotai commented on src/assets/details/plusIcon.svg
ใช้ `iconify` แทน

2024-01-13 18:39 UTC, boomchanotai commented on src/assets/details/chess.svg
ไม่เห็นมีใช้ละหนิ ลบเลย

2024-01-14 06:38 UTC, TeeGoood commented on src/components/Pets/details/PetImgList.tsx
> +        <img src={plusIcon} alt="plus-icon" />
component นี้ไม่ใช้ละ กูลบเลย

2024-01-14 07:02 UTC, TeeGoood commented
ที่เพิ่มรูปไม่ได้เกิดจากมีฟังชันนึงของกูมันจะเซ็ตรูปใหม่ทุกครั้งที่ rerender  กูเลยครอบ useEffect ไปละ 
ฟังก์ชันชื่อ convertImgToFile ใน BigPetCard.tsx

2024-01-14 07:10 UTC, Kchanatipz commented
ทักครับ

2024-01-14 07:22 UTC, boomchanotai requested changes
Commented !

2024-01-14 07:22 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
> +              />
ฝาก Link ไปที่ `/pets/:id/adopt`

2024-01-14 07:22 UTC, boomchanotai commented on src/components/Pets/Details/BigPetCard.tsx
ฝากใช้ breakpoint `md` แทนหน่อย

<img width="1552" alt="Screenshot 2567-01-14 at 14 16 39" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/547b1872-b2ee-479c-bf57-d2a8d44221e0">

2024-01-14 07:22 UTC, boomchanotai commented on src/components/Pets/Details/BigPetCard.tsx
แบบให้ iPad มันเป็นเหมือนคอมอ่ะ เฉพาะตรง `Container` บน

2024-01-14 07:22 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
> +              />
เวลาแก้ข้อมูล แล้วยังไม่ save พอกด submit แล้วมัน revert ไม่ save เลย

2024-01-14 10:10 UTC, TeeGoood commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
> +              />
กูเเก้ตรง showInfo ไปนะคือใน code มันไปสร้าง state ใหม่เวลาเเก้ไขข้อมูลมันเลยไม่ได้เเก้ที่ข้อมูลจริงๆ

2024-01-14 10:18 UTC, boomchanotai requested changes
Commented !

2024-01-14 10:18 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
> +              <Link to="/pets/:id/adopt">
`:id` เปลี่ยนไปเป็น ตัวแปร id ด้วย เอา `id` มาจาก Params ลองดูไฟล์ `/pets/[id]/adopt` ของไอเปา

2024-01-14 10:18 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
คลิกนอกกรอบข้อความยังไม่ถือว่า save ได้ไหม คือตอนนี้มัน save เวลาคลิกนอก input textbox อ่ะ

2024-01-14 10:18 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
ปุ่ม หัวใจ เอา state มารับด้วย และเตรียม function ไว้ให้ด้วย เดี๋ยวต้องกด fav

2024-01-15 09:55 UTC, boomchanotai approved these changes

2024-01-15 09:56 UTC, merged