feat: add horo game
isd-sgcu/johnjud-frontend pull request #25
Opened 2024-01-09 09:09 UTC by punchanabu

2024-01-11 06:43 UTC, boomchanotai requested changes
ฝากลบไฟล์ที่ไม่ได้ใช้แล้วหน่อยๆ

2024-01-11 06:43 UTC, boomchanotai commented on src/assets/horo/Horo - Game (/Icon/24 px/DownloadSimple.svg
ไฟล์นี้ไม่ได้ใช้แล้วหนิ เห็นว่าไปใช้ iconify แทน

2024-01-11 06:43 UTC, boomchanotai commented on src/assets/horo/Horo - Game (/Icon/24 px/Icon/24 px/Icon.svg
ไฟล์นี้ไม่ได้ใช้แล้วหนิ เห็นว่าไปใช้ iconify แทน

2024-01-11 06:43 UTC, boomchanotai commented on src/assets/horo/line.svg
ไฟล์นี้คืออะไรอ่ะ

2024-01-11 15:04 UTC, punchanabu commented on src/assets/horo/line.svg
มันคือเส้นของหน้าเลือกการ์ดอะ เส้นสีเหลืองๆที่ติดกับอุ้งมือแมว

2024-01-11 15:06 UTC, punchanabu commented on src/assets/horo/line.svg
แต่ลบไปใช้ iconify และ

2024-01-11 15:38 UTC, punchanabu commented
fix!

2024-01-11 16:01 UTC, boomchanotai requested changes
Commented!

2024-01-11 16:01 UTC, boomchanotai commented on src/components/Divider.tsx
> +  };
ฝากครอบอันนีด้วย useMemo ด้วย จะได้ cache ไว้

2024-01-12 06:38 UTC, boomchanotai approved these changes
LGTM !

2024-01-12 06:40 UTC, merged