chanatpakorn/feat:adopt page
isd-sgcu/johnjud-frontend pull request #28
Opened 2024-01-10 13:28 UTC by ChanatpakornD

- added adopt page
- modified PetBadge, Creating new props editable
- added Temporary petThumbnails for test page

2024-01-10 15:57 UTC, boomchanotai requested changes
พรี่เปาสุดยอดเลยคัฟ โค้ดดีมากๆคัฟ

2024-01-10 15:57 UTC, boomchanotai commented on src/app/adopt/page.tsx
> +        <PetThumbnails petLink="https://f.ptcdn.info/251/076/000/r6phkmmxuGNF1erTdMG-o.jpg" />
Wrap this Components with `div` contains class `max-h-80 max-w-80`

2024-01-10 15:57 UTC, boomchanotai commented on src/app/adopt/page.tsx
> +      </Container>
Don't wrap this with `Container` please copy `div` which wrap back icon from `src/app/admin/pets/add/page.tsx`

2024-01-10 15:57 UTC, boomchanotai commented on src/app/adopt/page.tsx
> +      <Container className="flex flex-col items-center gap-6 py-10 md:flex-row md:items-start md:justify-between">
Change `gap-6` to `gap-8` (เดิมใน figma เป็น Auto แต่เอาเป็น gap-8 ดีกว่า จะได้เหมือนในหน้า admin)

2024-01-10 15:57 UTC, boomchanotai commented on src/components/TermsAndConditions/index.tsx
> +        ></Button>
Add link to [https://www.facebook.com/CUVETforAnimalWelfareClub/](https://www.facebook.com/CUVETforAnimalWelfareClub/)

2024-01-10 15:57 UTC, boomchanotai commented on src/components/PetThumbnails/index.tsx
- ฝากทำให้ Components รับได้หลายรูป และทำเป็น Slideshow ได้หน่อยคัฟ
- ย้ายไปเก็บใน `src/components/Pets`

ใช้ [react-responsive-carousel](https://www.npmjs.com/package/react-responsive-carousel) ได้

2024-01-10 15:57 UTC, boomchanotai commented on src/components/TermsAndConditions/index.tsx
อันนี้ย้ายไปเก็บใน `src/components/Pets` หน่อยคัฟ

2024-01-10 15:59 UTC, boomchanotai requested changes
ฝากด้วยคัฟ

2024-01-10 15:59 UTC, boomchanotai commented on src/app/adopt/page.tsx
ย้ายไฟล์นี้ไปเก็บที่ `src/app/pets/[id]/adopt`

2024-01-11 02:26 UTC, ChanatpakornD commented
thx for your helping and `@everyone` who give me the essential code, especially @Kchanatipz

2024-01-11 03:00 UTC, boomchanotai approved these changes
LGTM !

2024-01-11 03:01 UTC, merged

2024-01-11 03:01 UTC, ChanatpakornD commented
@#$%^(