Feature/joh 13 login register
isd-sgcu/johnjud-frontend pull request #4
Opened 2023-12-21 13:46 UTC by punchanabu

## The things that  I do
- register and login UI in app/login and app/register
- add color johnjud-light-gray for the input background in tailwind.config.js
- add form icon in assets
- add Form component in component/Form

2023-12-21 14:44 UTC, boomchanotai requested changes
มีนิดนึง อยากให้ submit button อยู่ใน component เดียวกับ form และอยู่ใต้ tag `<form></form>` เพราะว่า เดี๋ยวตอน Integrate api เข้าไปจะได้ใช้ [react-hook-form](https://react-hook-form.com/) ได้เลย

2023-12-21 14:44 UTC, boomchanotai commented on src/components/Form/SubmitButton.tsx
> +    <button className="w-full text-nowrap rounded-3xl bg-primary px-28 py-3 text-2xl font-semibold text-white focus:outline-none">
ฝากใส่ type="submit" หน่อย

2023-12-21 16:33 UTC, punchanabu commented
แก้ละะ
- move submitButton to be the child of the form 
- add type = "submit" to submitButton component

2023-12-22 14:46 UTC, boomchanotai approved these changes
LGTM !

2023-12-22 15:12 UTC, merged