Chanatip/joh 60 sprint 4 reset password
isd-sgcu/johnjud-frontend pull request #41
Opened 2024-01-18 03:44 UTC by Kchanatipz

- add reset password page
- change file path for favourite and forget password

2024-01-18 11:29 UTC, boomchanotai requested changes
Refactor หน้าให้หน่อย

- เอาให้ Input หน้า `reset-password`, `login`, `forget-password` มันขนาดเท่ากัน (เอากว้าง `w-80 ให้หมดละกัน`) และก็หน้า reset-password อ่ะ icon input มันไม่ชิดซ้ายเหมือนหน้า forget-password
- เอาหน้า login อยู่ที่ `/admin` เลย ไม่ต้อง `/admin/login`
- จัดการเรื่องปุ่ม "ลืมรหัสผ่าน", "กลับไปหน้า login" ให้ลิ้งค์ไป path ที่ถูกต้องด้วย

2024-01-22 08:57 UTC, boomchanotai requested changes
- ลบ /register ออกเลย
- ใส่ react-form-hook ให้ login และ forgetpassword ด้วย

2024-01-22 08:57 UTC, boomchanotai commented on src/app/admin/forget-password/page.tsx
> +        <div className="wflex flex-row items-center justify-center">
WTF is `wflex`

2024-01-22 08:57 UTC, boomchanotai commented on src/app/admin/reset-password/page.tsx
> +        </Link>
เอาไปใส่ข้างใน `<form></form>` แล้วก็ เพิ่ม Props `submit` ด้วย ถ้าเป็น `true` จะเป็น type="submit" ถ้า false type="button"

2024-01-22 09:09 UTC, Kchanatipz commented on src/app/admin/forget-password/page.tsx
> +        <div className="wflex flex-row items-center justify-center">
5555555

2024-01-22 09:11 UTC, Kchanatipz commented on src/app/admin/reset-password/page.tsx
> +        </Link>
หมายถึงถ้าprop submitเป็นtrueกลายเป็นsubmit แต่falseจะเป็นbuttonช่ะ

2024-01-29 11:51 UTC, boomchanotai requested changes
- ให้ทำตัว useFromHook ของ Login, Forget Password เหมือน reset password ด้วย
- ลบ /register ไปเลย

2024-02-03 13:41 UTC, closed without merging