refactor: add answer
isd-sgcu/johnjud-frontend pull request #44
Opened 2024-01-22 04:22 UTC by TeeGoood

ez

2024-01-22 08:46 UTC, boomchanotai requested changes
commented!

2024-01-22 08:46 UTC, boomchanotai commented on src/app/frequently-asked-questions/page.tsx
>      question: "พรี่บูมรักแมวมากจนต้องนอกใจหมาได้ไหม",
เปลี่ยนหัวข้อด้วยโว้ยย

2024-01-22 14:51 UTC, TeeGoood commented on src/app/frequently-asked-questions/page.tsx
>      question: "พรี่บูมรักแมวมากจนต้องนอกใจหมาได้ไหม",
55555

2024-01-23 10:17 UTC, boomchanotai approved these changes
LGTM!

2024-01-24 14:06 UTC, merged