Chanatpakorn/joh 58 sprint 4 download and share
isd-sgcu/johnjud-frontend pull request #47
Opened 2024-01-25 11:57 UTC by ChanatpakornD

- add Download and Share to Horo Page

![petHoro-The High Priestess](https://github.com/isd-sgcu/johnjud-frontend/assets/113345557/b6767cbb-c506-4363-8fb4-eac4dded2520)

minor bug?? : help me!

2024-01-29 11:55 UTC, boomchanotai requested changes
/game รูปไม่ขึ้น

![JohnJud result](https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/7787442d-2b09-440d-8da7-fc3ad8a516ba)

2024-01-29 19:28 UTC, ChanatpakornD commented
- Implementing download and share to `/game` and `/horo`
- deployment failed จากไรวะ
- canvas so hard, i'm using plain canvas for now
- Art later

2024-02-16 04:31 UTC, ChanatpakornD commented
- Changing to use picture assets instead
- Change some wrong result in Horo
- Rename utils download and share

2024-02-16 09:20 UTC, boomchanotai requested changes

2024-02-16 09:20 UTC, boomchanotai commented on .env.example
เอามันกลับมา

2024-02-16 09:20 UTC, boomchanotai commented on src/utils/Results.ts
rename to `gameResult`

2024-02-16 09:20 UTC, boomchanotai commented on src/utils/horo.ts
rename to `horoResult`

2024-02-16 09:20 UTC, boomchanotai commented on src/utils/shareResult.ts
อันนี้ใช้หรอ

2024-02-16 12:10 UTC, ChanatpakornS commented on src/utils/shareResult.ts
deleted in the new commit

2024-02-16 12:12 UTC, ChanatpakornD commented
- refactor filename
- sorry for .env.example deletion
- deleted canvas-txt lib and shareResult since it's no use
-

2024-02-16 12:57 UTC, boomchanotai approved these changes

2024-02-16 13:23 UTC, merged