feat: add api admin auth [Login, Register, Forget Password, Reset Password] (Mutation) (Zustand)
isd-sgcu/johnjud-frontend pull request #48
Opened 2024-01-27 04:46 UTC by punchanabu

2024-02-01 12:48 UTC, boomchanotai requested changes
- ถ้า user login แล้ว แล้วเข้า /login ให้ redirect ไปที่ /home
- ถ้า user login แล้ว แล้วเข้า /forget-password ให้ redirect ไปที่ /home
- Implement หน้า /forget-password กับ /reset-password ด้วย (หน้า register ไม่ต้อง เดี๋ยวต้องลบ)
- ฝากทำแบบ session validate ให้ด้วย ใส่ใน component Navbar ก็ได้

2024-02-01 12:48 UTC, boomchanotai commented on src/hooks/auth/useSignUp.ts
ลบได้เลย ไม่มีระบบ register ละ

2024-02-01 12:48 UTC, boomchanotai commented on src/api/auth/signUp.ts
ลบได้เลย ไม่มีระบบ register ละ

2024-02-01 14:35 UTC, punchanabu commented
wait na refresh page laew state reset. token hai pai.

2024-02-03 09:02 UTC, punchanabu commented
## Change
### implement reset-password / forget-password 
- ก๊อบ component ของ sun มา implement จาก admin/reset-password และ
 admin/forget-password แต่ยัง test ไม่ได้ เพราะ Margin บอกว่า มันใช้ sendgrid api ซึ่งมันต้องใช้เมล isd เพื่อสร้างบัญชี sendgrid แต่ตอนนี้ยังไม่มีบัญชีแต่ที่เข้าใจคือตอนส่งเมลมามันจะเป็น [https://github.com/isd-sgcu/johnjud-gateway/pull/26](url) แนวนี้เลยเขียนแบบตัด url เอา เพื่อจะเอา token ไว้
### Session validate
- ทำ session validate แล้วใน navbar ถ้า token หมดอายุให้สั่ง refreshtoken ใหม่
### Redirect
- redirectตามที่ขอมาละ
### Delete SignUp
- ลบ SignUp ทิ้งไปละ

2024-02-03 13:40 UTC, boomchanotai requested changes
- งั้นฝากย้าย `/login` เป็น `/admin` เลย ลบหน้าเก่าไปเลย เพราะว่าไม่มีให้ user login ละ มีแค่ให้ admin login
- ลบ `/forget-password` แล้วใช้ `/admin/forget-password` ไปแทนเลย

2024-02-03 13:40 UTC, boomchanotai commented on src/app/admin/forget-password/page.tsx
> +  const forgetPassword = useForgetPassword();
แตก `mutation` ออกมาเหมือน `reset-password` เลยก็ได้นะ

2024-02-03 13:40 UTC, boomchanotai commented on src/app/forget-password/page.tsx
ลบเลยละกัน ใช้แค่ `/admin/forget-password` แทน

2024-02-03 13:40 UTC, boomchanotai commented on src/app/login/page.tsx
ย้ายไปที่ `/admin` แทน

2024-02-03 13:40 UTC, boomchanotai commented on src/components/Form/LoginForm.tsx
ใช้ `react-form-hook` แทน `useState`

2024-02-13 09:40 UTC, boomchanotai requested changes
- พอ login เสร็จให้ Redirect ไปที่หน้า `/admin/pets` แล้วก็ทุกครั้งที่ Login แล้ว แล้วไปที่หน้า `/admin` ให้มัน redirect เข้า `/admin/pets` ตลอดเลย
- `/admin` หน้า Login ปุ่ม `ลืมรหัสผ่าน` ฝากแก้ให้ redirect ไป `/admin/forget-password` หน่อย
- `/admin/forget-password` ปุ่มกดกลับไปที่หน้า Login ให้ redirect ไปที่ `/admin`

2024-02-14 04:38 UTC, boomchanotai requested changes
- แก้ api
- implement forget password อีกนิดนึง

2024-02-14 04:38 UTC, boomchanotai commented on src/api/auth/password/forgotPassword.ts
> +    `${import.meta.env.VITE_API_URL}/auth/password/forgot-password`,
- api : `/auth/forget-password`
- Please Implement forget password (ทำแค่มันส่งฟอร์มได้ก่อน เหมือนเส้นนี้จะยังไม่เสร็จมั้ง แบบให้กด submit form แล้วมันส่งข้อมูลไปอ่ะ ตอบกลับอะไรมาก็ช่างมัน แล้ว redirect ไปที่หน้า`/admin` (หน้า login))

2024-02-14 04:38 UTC, boomchanotai commented on src/api/auth/password/resetPassword.ts
> +    `${import.meta.env.VITE_API_URL}/auth/password/reset-password`,
`/auth/reset-password`

2024-02-14 08:48 UTC, punchanabu commented on src/api/auth/password/forgotPassword.ts
> +    `${import.meta.env.VITE_API_URL}/auth/password/forgot-password`,
> * api : `/auth/forget-password`
> * Please Implement forget password (ทำแค่มันส่งฟอร์มได้ก่อน เหมือนเส้นนี้จะยังไม่เสร็จมั้ง แบบให้กด submit form แล้วมันส่งข้อมูลไปอ่ะ ตอบกลับอะไรมาก็ช่างมัน แล้ว redirect ไปที่หน้า`/admin` (หน้า login))

- ทำให้มันส่งฟอร์มได้และแต่เปลี่ยนเวลากด submit ของ forget-password แล้วจะขึ้น pop-up มาแล้วให้ user กดไปหน้า /admin เองละกัน

2024-02-16 08:21 UTC, boomchanotai approved these changes
LGTM!

2024-02-16 09:56 UTC, merged