Thanaphomh/joh 72 sprint 5 api admin add pets adminpetsadd mutation
isd-sgcu/johnjud-frontend pull request #49
Opened 2024-02-03 06:13 UTC by ThanaphomH

- hook api for POST at /images and /pets/create (currently there is no auth token so I cannot fully test it)
- change some info field into dropdown selection
- for age field, wait to confirm if it to be an exact date or normal string (currently is normal string)
- remove "-" when click edit info
- disable submit button when not provide some important field

2024-02-03 13:57 UTC, boomchanotai requested changes

2024-02-03 13:57 UTC, boomchanotai commented on src/api/createPets.ts
ไฟล์ชื่อ `pet.ts` เลยๆ ข้างในเป็น function `createPet` แล้วก็ export มาแบบ `export { createPet }` ในไฟล์นี้น่าจะต้องยำ พวก getPet getPets deletePet มาใส่ด้วย

2024-02-03 13:57 UTC, boomchanotai commented on src/app/admin/pets/add/page.tsx
`birthdate` เอาเป็น `datepicker` เลย แบบ `input type="date"` อ่ะ

2024-02-03 13:57 UTC, boomchanotai commented on src/components/Admin/Pets/Add/EditInfoAndSubmit.tsx
ช่องที่ให้กรอก นิสัยกับวันเกิน ขอ padding-y เท่ากับกล่อง select

2024-02-13 10:03 UTC, boomchanotai requested changes
- iPad เวลาแก้ไขชื่อ เอาให้ ชิดซ้าย แต่โทรศัพท์ชิดขวาเหมือนเดิม
<img width="523" alt="Screenshot 2567-02-13 at 17 01 51" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/53d6f35f-644d-494e-8cad-454860194d61">

- Image ส่งได้ละนะ เป็น Formdata ฝากทำส่ง image ด้วย
- Auth Token ไม่ต้องส่งคำว่า Bearer ไป Margin แจ้งมาละ แต่ทำไม create pets ไม่ได้ไม่รู้ เดะลองถามดู

2024-02-15 14:44 UTC, ThanaphomH commented
- post pet ปัจจุบันมันไม่มี is_club_pet : boolean แล้ว แต่เป็น origin : string แทน ผมแก้ไปแค่ที่ต้อง request ของ post /pets แต่ไม่ได้แก้ที่ type Pets ใหญ่นะ
-  auth ตอนนี้ยังต้องใส่ Bearer อะ
-  image ของ pet ที่โพสไป ตอนนี้ไม่ว่าจะส่งอะไรไป มันก็แปะรูปมั่วๆให้ 4 รูป อันนี้ระบบด้านหลังน่าจะยังไม่เสร็จ (รึเปล่า)

2024-02-16 09:47 UTC, boomchanotai approved these changes

2024-02-16 10:15 UTC, merged