feat: Q&A page
isd-sgcu/johnjud-frontend pull request #6
Opened 2023-12-21 18:37 UTC by ChanatpakornD

- Add Q&A page
- Add more SVG in public
- Add a new component (QuestionBox)

//problem//
- BG automatically zoomed in after open the answer panel

2023-12-22 15:10 UTC, boomchanotai requested changes
เรื่อง background ไปลองดูละ ลองไปที่ไฟล์ MainLayout แล้วก็เปลี่ยนคลาสเป็น `bg-auto bg-top`

2023-12-22 15:10 UTC, boomchanotai commented on src/app/faq.tsx
อ่านนี่ซะ คือทำ folder ที่เป็นชื่อ path จากนั้น ใส่ page.tsx ลงไป

แล้วเติม export const Layout = MainLayout ด้วย

<img width="787" alt="Screenshot 2566-12-22 at 22 04 14" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/18429d50-2726-48c7-a727-6f583ff87fc2">

2023-12-22 15:10 UTC, boomchanotai commented on src/app/faq.tsx
> +      <div className="relative  mt-9 px-10 pb-16 text-teal-600">
ฝากใส่ max-w-sm ด้วย เวลา จอใหญ่มันจะได้ไม่ขยายเต็มหน้าจอ

2023-12-23 09:34 UTC, ChanatpakornD commented
- Add new Folder (Faq) at /app
- Add Layout to code / change bg layout / add max-w-sm

2023-12-23 18:16 UTC, boomchanotai requested changes
มีอีกนิดนึง
1. `img` ใช้ import ทั้งหมด (อ่านเพิ่มเติมใน comment ตรงไหนสักที่) [react-docs](https://create-react-app.dev/docs/adding-images-fonts-and-files/)
2. ลบไฟล์เก่าด้วย faq.tsx อ่ะ
3. โฟลเดอร์ให้เป็นชื่อตัวเล็ก
4. ฝากเพิ่ม space ตรงระหว่างข้อความกับ icon ลงหน่อย

<img width="601" alt="Screenshot 2566-12-24 at 01 14 00" src="https://github.com/isd-sgcu/johnjud-frontend/assets/13506569/a1b02faa-282e-4aa8-b133-f6860b6d0a27">

2023-12-23 18:16 UTC, boomchanotai commented on src/app/faq.tsx
ลบออก !!

2023-12-23 18:16 UTC, boomchanotai commented on src/app/faq.tsx
หมายถึงทั้งไฟล์อ่ะ

2023-12-23 18:16 UTC, boomchanotai commented on src/components/QuestionBox.tsx
> +              src="../../public/question_icon.svg"
`img` ให้ใช้เป็น import แทน ดูได้ที่ [react-docs](https://create-react-app.dev/docs/adding-images-fonts-and-files/)

คือ เก็บไฟล์ไว้ใน folder `src/assets` จะสร้างโฟลเดอร์ใหม่หรือยังไงก็ตามแต่ แล้วเวลาเรียกใช้ก็ import มา

2023-12-23 18:16 UTC, boomchanotai commented on src/components/QuestionBox.tsx
> +          src="../../public/back_icon.svg"
นี่ก็ด้วย import มา

2023-12-23 18:16 UTC, boomchanotai commented on src/app/Faq/page.tsx
> +            <img src="../../public/bubble.svg" alt="_blank" />
import image มา

2023-12-24 05:04 UTC, ChanatpakornD commented
- Edit img -> import like ur orders
- Add ur provide codes to `routes.tsx`
- Add new folder assets

2023-12-24 08:27 UTC, boomchanotai requested changes
อย่าลืมเปลี่ยนชื่อ folder จาก `src/app/Faq` เป็น `src/app/faq`

2023-12-24 08:27 UTC, boomchanotai commented on src/components/QuestionBox.tsx
> +    <div className="mb-6 flex flex-col rounded-3xl bg-white shadow-lg">
ฝากใส่ `cursor-pointer` หน่อย

2023-12-24 10:22 UTC, ChanatpakornD commented
- Add `cursor-pointer`
- Change from `src/app/faq` to `src/app/frequently-asked-questions` due to Capital letter

2023-12-24 13:11 UTC, boomchanotai approved these changes
เก่งมากคัฟพรี่เปา

2023-12-24 13:15 UTC, merged