Tee/sprint 5/admin edit api
isd-sgcu/johnjud-frontend pull request #71
Opened 2024-02-20 13:14 UTC by TeeGoood

- add useEffect to EditInfoAndSubmit and DropDownInputInfo because of some bug
- add delete image codes in Detail.tsx 's handleSubmit (but are commented right now) to clear old picture pet and then post new one

2024-02-24 15:14 UTC, TeeGoood commented
- remove BigPetCard.tsx and move its content to Detail.tsx
- remove unused file 
- remove unused folder

2024-02-25 13:13 UTC, boomchanotai requested changes

2024-02-25 13:13 UTC, boomchanotai commented on dfasf
WTF is this

2024-02-25 13:13 UTC, boomchanotai commented on src/app/admin/pets/page.tsx
> +          <PetPageFallback />
ทำไมถึงเปลี่ยน จาก Pets เป็น Pet

2024-02-25 13:13 UTC, boomchanotai commented on src/app/admin/users/page.tsx
ไม่มีหน้านี้แล้ว ลบเลย

2024-02-25 13:13 UTC, boomchanotai commented on src/app/example/[id]/page.tsx
ไม่มีแล้ว ลบเลย

2024-02-25 13:13 UTC, boomchanotai commented on src/app/example/page.tsx
ไม่มีแล้ว ลบเลย

2024-02-25 13:13 UTC, boomchanotai commented on src/app/forget-password/page.tsx
ลบ

2024-02-25 13:13 UTC, boomchanotai commented on src/components/Admin/Pets/Add/OptionInputInfo.tsx
อันนี้ทำใหม่หรอ หรือของดน

2024-02-25 13:13 UTC, boomchanotai commented on src/components/Main/CardList/BigPetCardContainer.tsx
เปลี่ยนชื่อแล้ว อันนี้ลบเลย

2024-02-25 13:13 UTC, boomchanotai commented on src/components/Main/CardList/MiniPetCardContainer.tsx
เปลี่ยนชื่อแล้ว อันนี้ลบเลย

2024-02-25 13:13 UTC, boomchanotai commented on src/hooks/queries/usePetsAdminQuery.ts
อันนี้มันของ margin ป่ะ ทำไมมันขึ้นว่าทำใหม่ทั้งไฟล์

2024-02-25 13:13 UTC, boomchanotai commented on src/components/Modal/EmailVerification.tsx
เปลี่ยนแล้ว ลบเลย

2024-02-25 13:47 UTC, TeeGoood commented on src/components/Admin/Pets/Add/OptionInputInfo.tsx
ของดนๆ

2024-02-25 13:51 UTC, TeeGoood commented on src/hooks/queries/usePetsAdminQuery.ts
ใช่ มันบอกว่าขึ้นใหม่เพราะตอนกู merge เเล้วมันไม่ขึ้นเลย ก็อปวางเอา

2024-02-25 13:56 UTC, boomchanotai commented on src/components/Admin/Pets/Add/OptionInputInfo.tsx
ลบๆ

2024-02-25 13:57 UTC, boomchanotai requested changes

2024-02-25 13:57 UTC, boomchanotai commented on src/components/Pets/Details/BigPetCard.tsx
อันนี้ไม่ลบๆ

2024-02-25 14:08 UTC, closed without merging