Feature/joh 14 main page
isd-sgcu/johnjud-frontend pull request #9
Opened 2023-12-25 16:40 UTC by Kchanatipz

@Main page

2023-12-25 17:38 UTC, boomchanotai requested changes
1. ทำให้เต็มจอ + แมวชิดขอบล่างตามที่ comment ไป
2. ย้ายทั้งหมดนี้ไปใส่ใน `src/app/page.tsx` แทน เพราะมันเป็นหน้าแรก

// อย่าลืมใส่ `export const Layout = MainLayout` ที่บรรทัดล่างสุดด้วย

2023-12-25 17:38 UTC, boomchanotai commented on src/app/main/page.tsx
> +    <div className="w-full shrink-0 bg-primary pt-7 xl:pt-16">
บรรทัดนี้เติม `min-h-screen` ให้หน่อย มันจะทำให้กว้างเท่ากับหน้าจอ

2023-12-25 17:38 UTC, boomchanotai commented on src/app/main/page.tsx
> +    <div className="w-full shrink-0 bg-primary pt-7 xl:pt-16">
แล้วก็ใช้ `flex flex-col justify-between` มันจะดัน element ชิดบน กับชิดล่าง ทำให้แมวอยู่ชิดล่าง

2023-12-26 03:40 UTC, Kchanatipz commented on src/app/main/page.tsx
> +    <div className="w-full shrink-0 bg-primary pt-7 xl:pt-16">
ละให้กุลบfolder mainกับpage.tsx(ในนั้น)ที่สร้างมา

2023-12-26 08:03 UTC, boomchanotai requested changes
ลบ `src/app/main` ออกด้วย ทั้ง folder ละไฟล์เลย

2023-12-26 15:29 UTC, boomchanotai approved these changes
Perfect !

2023-12-26 15:33 UTC, merged